### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by venaxyt**

### CODE REVIEW

**Comment by marcus-alicia** [comment]
one small thing, crypto requires vs build tools which is why I would not recommend it. pain to get it to work

**Comment by venaxyt** [comment]
> 

Oh I didn't know that, I did not notice it since I already have build tools, thanks for the information, and for your precious work on this grabber, thanks to you I got able to update the private mine x)

**Comment by marcus-alicia** [comment]
no problem @venaxyt . ive been working on discord related stuff for years now. if u got any questions about anything discord, or coding / security related in general feel free to drop your discord to chat

**Comment by venaxyt** [comment]
Thanks you very much, I will if I need ;)

**Pull request merged**
